### PR TITLE
Implement JSON binary encoding

### PR DESCRIPTION
**Pull request by willks**
Added binary support for JSON along with tests

### CODE REVIEW

**Comment by vietj** [comment]
I think we need to handle other possible types such as `JsonArray`

**Comment by willks** [comment]
Will implement array as part of this PR.

**Comment by willks** [comment]
Have JSON array working fine, the pain point is the scalar queries. Working on that in order to complete this PR

**Comment by willks** [comment]
Closing PR due to issues with scalar bind queries. Needs a bit more tinkering. JsonObject and JsonArray completed

**Pull request closed without merging**
