### PR TITLE
Add document for PgResult

### PR DESCRIPTION
**Pull request by BillyYccc**

### CODE REVIEW

**Comment by vietj** [comment]
@BillyYccc before merging your PR I need to ask you if you comply with the CLA I set on this project, which basically you need to agree with the copyright on the project and swear you did not steal any code anywhere :-)

**Comment by BillyYccc** [comment]
@vietj Yes, I do agree with the CLA! :) Also, do I have to sign like that in Vert.x Projects?

**Comment by vietj** [comment]
it's a diffrent project, I haven't set formally anything (yet), perhaps I'll ask something more formal later.

**Comment by BillyYccc** [comment]
Maybe [Code of Conduct](https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/) is suitable for this.

**Comment by vietj** [comment]
@BillyYccc no, CoC are a different things, they don't care about IP or due diligence, they care about people not being asses :-)

**Pull request merged**
